In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns', None)

In [3]:
 # Plot settings
plt.rcParams["figure.figsize"] = (12, 6)
sns.set(style="whitegrid")

raw = "../data/raw"

In [4]:
# Load all datasets
sales = pd.read_csv(f"{raw}/sunnybest_sales.csv", parse_dates=["date"])
products = pd.read_csv(f"{raw}/sunnybest_products.csv")
stores = pd.read_csv(f"{raw}/sunnybest_stores.csv")
calendar = pd.read_csv(f"{raw}/sunnybest_calendar.csv", parse_dates=["date"])
promos = pd.read_csv(f"{raw}/sunnybest_promotions.csv", parse_dates=["date"])
weather = pd.read_csv(f"{raw}/sunnybest_weather.csv", parse_dates=["date"])
inventory = pd.read_csv(f"{raw}/sunnybest_inventory.csv", parse_dates=["date"])


# surpress warning

# warnings.filterwarnings("ignore", category=DtypeWarning)

/var/folders/rt/0zxshr9s4g713_r6y5sjpqk80000gn/T/ipykernel_45300/3054379081.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  sales = pd.read_csv(f"{raw}/sunnybest_sales.csv", parse_dates=["date"])

In [5]:
df = (
    sales
    .merge(products, on="product_id", how="left", suffixes=("", "_product"))
    .merge(stores, on="store_id", how="left", suffixes=("", "_store"))
    .merge(calendar, on="date", how="left", suffixes=("", "_cal"))
    .merge(weather, on=["date", "city"], how="left", suffixes=("", "_weather"))
    .merge(promos, on=["date", "store_id", "product_id"], how="left", suffixes=("", "_promo"))
)

print(df.shape)
df.head()

(1227240, 43)

,date,store_id,product_id,units_sold,price,regular_price,discount_pct,promo_flag,promo_type,revenue,...,is_weekend,is_holiday,is_payday,season,temperature_c,rainfall_mm,weather_condition,promo_type_promo,discount_pct_promo,promo_flag_promo
0,2021-01-01,1,1001,0,445838.0,445838,0,0,NaN,0.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
1,2021-01-01,1,1002,2,500410.0,500410,0,0,NaN,1000820.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
2,2021-01-01,1,1003,2,399365.0,399365,0,0,NaN,798730.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
3,2021-01-01,1,1004,4,305796.0,305796,0,0,NaN,1223184.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
4,2021-01-01,1,1005,5,462752.0,462752,0,0,NaN,2313760.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN

## Stores Data Overview & Business Context

The stores dataset provides **static reference information** about each physical retail location.  
Each row represents **one store**, describing its geographical location and operational scale.  
This data does not change daily and is used to **add contextual information** to sales records rather than to record sales events themselves.

---

### Store Data Grain

- **One row = one store**
- The dataset grows only when:
  - a new store opens, or  
  - store attributes are updated

---

### Key Store Columns & Meanings

| Column | Business Meaning |
|------|------------------|
| store_id | Unique identifier for a physical retail store |
| city | City in which the store is located |
| store_size | Classification of store scale (e.g. Small, Medium, Large), reflecting capacity and expected footfall |

---

### How This Data Is Used

Store attributes are **joined onto the sales data** to help explain differences in demand and performance across locations.  
For example, larger stores or stores in certain cities may consistently sell higher volumes than others.

---

### Important Note

The stores dataset **does not record sales**.  
It provides **context** that helps interpret sales outcomes observed in the daily sales dataset.

In [6]:
df.head()

,date,store_id,product_id,units_sold,price,regular_price,discount_pct,promo_flag,promo_type,revenue,...,is_weekend,is_holiday,is_payday,season,temperature_c,rainfall_mm,weather_condition,promo_type_promo,discount_pct_promo,promo_flag_promo
0,2021-01-01,1,1001,0,445838.0,445838,0,0,NaN,0.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
1,2021-01-01,1,1002,2,500410.0,500410,0,0,NaN,1000820.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
2,2021-01-01,1,1003,2,399365.0,399365,0,0,NaN,798730.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
3,2021-01-01,1,1004,4,305796.0,305796,0,0,NaN,1223184.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
4,2021-01-01,1,1005,5,462752.0,462752,0,0,NaN,2313760.0,...,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN

In [8]:
df.head()

,date,store_id,product_id,units_sold,price,regular_price,discount_pct,promo_flag,promo_type,revenue,starting_inventory,ending_inventory,stockout_occurred,city,store_size,category,product_name,category_product,brand,regular_price_product,cost_price,is_seasonal,warranty_months,store_name,city_store,area,region,store_type,store_size_store,year,month,day,day_of_week,is_weekend,is_holiday,is_payday,season,temperature_c,rainfall_mm,weather_condition,promo_type_promo,discount_pct_promo,promo_flag_promo
0,2021-01-01,1,1001,0,445838.0,445838,0,0,NaN,0.0,1,1,0,Benin,Large,Televisions,LG Televisions Model-120,Televisions,LG,445838,332772,1,6,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large,2021,1,1,Friday,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
1,2021-01-01,1,1002,2,500410.0,500410,0,0,NaN,1000820.0,6,4,0,Benin,Large,Mobile Phones,Tecno Mobile Model-199,Mobile Phones,Tecno,500410,346208,1,6,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large,2021,1,1,Friday,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
2,2021-01-01,1,1003,2,399365.0,399365,0,0,NaN,798730.0,2,0,1,Benin,Large,Mobile Phones,Tecno Mobile Model-905,Mobile Phones,Tecno,399365,244124,1,12,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large,2021,1,1,Friday,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
3,2021-01-01,1,1004,4,305796.0,305796,0,0,NaN,1223184.0,10,6,0,Benin,Large,Mobile Phones,Infinix Mobile Model-121,Mobile Phones,Infinix,305796,221242,1,12,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large,2021,1,1,Friday,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN
4,2021-01-01,1,1005,5,462752.0,462752,0,0,NaN,2313760.0,28,23,0,Benin,Large,Mobile Phones,Samsung Mobile Model-781,Mobile Phones,Samsung,462752,326219,1,24,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large,2021,1,1,Friday,False,True,False,Dry,30.6,3.7,Rainy,NaN,NaN,NaN

In [11]:
df.shape

(1227240, 43)